services:
  postgres:
    image: postgres:17

    container_name: clinic-postgres

    restart: unless-stopped

    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clinic

    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
